### PR TITLE
Allow CentOS 7 / RHEL 7

### PR DESCRIPTION
**Pull request by apatik**
Changes allow module to work with RHEL 7 and it's clones. Packages for this OS version are available via EPEL7, same as with RHEL 6 / EPEL6. Minimal changes were required, and the module version has already been Semantically incremented with a minor release bump.

Spec tests were also updated, although I haven't actually run them, as I haven't yet started using puppet-rspec in my environment. I assume your Travis-CI instance will pick up on any issues, but I'm fairly confident they're correct, given the simplicity of this module.

Let me know if there's any issues / further changes you require before accepting.

### CODE REVIEW

**Comment by jhoblitt** [comment]
Looks like travis had some sort of issue.  I've triggered a rebuild.

Could you remove the `metadata.json` and the changes to `Modulefile` from this PR?  I will insert a `metadata.json` as part of a general plumbing update before cutting a new release of this module.

**Comment by jhoblitt** [comment]
The test plumbing is going to need to updated to get the tests passing under travis.  I will try to get to that in the next day or two.

**Comment by apatik** [comment]
Module file and metadata.json reverted. Thanks for the quick response!

**Comment by jhoblitt** [comment]
This PR was rebased and merged as #4.  Thanks for contributing this!  Released as part of v0.3.0: https://forge.puppetlabs.com/jhoblitt/zeromq/0.3.0

**Pull request closed without merging**
